# Generated by Django 5.1.3 on 2024-11-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discord_id',
            field=models.SlugField(help_text='Discordのユーザーidを本人確認メールの送信に利用します。', max_length=20, unique=True, verbose_name='discord id'),
        ),
    ]
