# Generated by Django 5.1.3 on 2024-11-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_is_active_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discord_id',
            field=models.SlugField(help_text='DiscordのユーザーIDを本人確認メールの送信に利用します。', max_length=20, unique=True, verbose_name='Discord ID'),
        ),
    ]
