# Generated by Django 5.1.3 on 2024-11-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='discord_id',
            field=models.CharField(help_text='Discordのユーザー名を本人確認に利用します。', max_length=20, unique=True, verbose_name='Discordのユーザー名'),
        ),
    ]
