# Generated by Django 5.1.3 on 2024-11-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_email_alter_customuser_discord_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='discord_id',
            new_name='discord_username',
        ),
    ]
