# Generated by Django 5.1.3 on 2024-11-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('discord_id', models.SlugField(max_length=20, unique=True, verbose_name='Discord ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='discord_username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='discord_id',
            field=models.SlugField(default=0, help_text='DiscordのユーザーIDを本人確認に利用します。', max_length=20, unique=True, verbose_name='Discord ID'),
            preserve_default=False,
        ),
    ]
