# Generated by Django 5.1.3 on 2024-11-15 12:49

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_discorduser_remove_customuser_discord_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "同じユーザー名が既に登録済みです。"},
                help_text="この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。",
                max_length=127,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="discorduser",
            name="username",
            field=models.CharField(max_length=127, verbose_name="username"),
        ),
    ]
