# Generated by Django 5.1.3 on 2024-11-17 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_customuser_username_alter_discorduser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
    ]
