# Generated by Django 5.1.3 on 2024-11-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_discorduser_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discorduser",
            name="date_joined",
        ),
    ]
