# Generated by Django 5.1.3 on 2024-11-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_discorduser_date_joined"),
    ]

    operations = [
        migrations.CreateModel(
            name="TakingSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=127, unique=True, verbose_name="subject name"
                    ),
                ),
                ("grade", models.IntegerField(verbose_name="grade")),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="subject",
            field=models.ManyToManyField(
                blank=True, related_name="履修中教科", to="accounts.takingsubject"
            ),
        ),
    ]
