# Generated by Django 5.1.3 on 2024-11-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_takingsubject_customuser_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="schedule_id",
            field=models.IntegerField(
                blank=True,
                help_text="スケジュール詳細でIDを確認できます。",
                null=True,
                verbose_name="スケジュールID",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="subject",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="履修中教科",
                to="accounts.takingsubject",
            ),
        ),
    ]
