# Generated by Django 5.1.3 on 2024-11-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_customuser_schedule_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiscordUser",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="discord_id",
        ),
    ]
