# Generated by Django 5.1.3 on 2024-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_delete_discorduser_remove_customuser_discord_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(
                default="unknown",
                help_text="この項目はスケジュール完遂ユーザーで公開される名前です。",
                max_length=32,
                verbose_name="ニックネーム",
            ),
        ),
    ]
