# Generated by Django 5.1.3 on 2024-12-10 02:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_customuser_nickname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
