# Generated by Django 5.1.3 on 2024-12-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_remove_customuser_id_customuser_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="uuid",
            new_name="id",
        ),
    ]
