# Generated by Django 5.1.3 on 2024-12-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_rename_uuid_customuser_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="id",
            new_name="uuid",
        ),
    ]
