# Generated by Django 5.1.3 on 2024-11-26 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="カテゴリー名"
                    ),
                ),
                (
                    "bs_color",
                    models.CharField(max_length=32, verbose_name="Boostrap Color"),
                ),
                (
                    "bs_icon",
                    models.CharField(max_length=32, verbose_name="Bootstrap Icon"),
                ),
                (
                    "channel_id",
                    models.SlugField(max_length=20, verbose_name="チャンネルID"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="締め切り日")),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="教科名"),
                ),
                ("grade", models.IntegerField(verbose_name="学年")),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="課題プリント、中間テスト、証明写真など",
                        max_length=64,
                        verbose_name="タイトル名",
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True,
                        help_text="詳しい説明などはこちらに。空欄でも可。",
                        null=True,
                        verbose_name="詳細",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="unknown", max_length=64, verbose_name="作成者"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        default="unknown", max_length=64, verbose_name="編集者"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="変更日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reminder.category",
                        verbose_name="カテゴリー名",
                    ),
                ),
                (
                    "deadline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reminder.deadline",
                        verbose_name="締め切り日",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reminder.subject",
                        verbose_name="教科名",
                    ),
                ),
            ],
        ),
    ]
