# Generated by Django 5.1.3 on 2024-11-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deadline",
            name="week",
            field=models.CharField(
                choices=[
                    ("月", "月曜日"),
                    ("火", "火曜日"),
                    ("水", "水曜日"),
                    ("木", "木曜日"),
                    ("金", "金曜日"),
                    ("土", "土曜日"),
                    ("日", "日曜日"),
                ],
                default="月",
                max_length=2,
                verbose_name="曜日",
            ),
        ),
    ]
