# Generated by Django 5.1.3 on 2024-11-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="detail",
            field=models.TextField(
                blank=True,
                help_text="詳しい説明などはこちらに。空欄でも可。",
                verbose_name="詳細",
            ),
        ),
    ]
