# Generated by Django 5.1.3 on 2024-11-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0002_deadline_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deadline",
            name="week",
            field=models.CharField(
                choices=[
                    ("月曜日", "月曜日"),
                    ("火曜日", "火曜日"),
                    ("水曜日", "水曜日"),
                    ("木曜日", "木曜日"),
                    ("金曜日", "金曜日"),
                    ("土曜日", "土曜日"),
                    ("日曜日", "日曜日"),
                ],
                default="月曜日",
                max_length=3,
                verbose_name="曜日",
            ),
        ),
    ]
