# Generated by Django 5.1.3 on 2024-11-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0002_alter_memo_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="title",
            field=models.TextField(
                default=1,
                help_text="課題プリント、中間テスト、証明写真など",
                max_length=31,
                verbose_name="タイトル名",
            ),
            preserve_default=False,
        ),
    ]
