# Generated by Django 5.1.3 on 2024-11-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0003_alter_deadline_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="channel_id",
        ),
        migrations.AddField(
            model_name="category",
            name="webhook_url",
            field=models.SlugField(
                default=0, max_length=128, verbose_name="Webhook Url"
            ),
            preserve_default=False,
        ),
    ]
