# Generated by Django 5.1.3 on 2024-11-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0003_memo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="title",
            field=models.CharField(
                help_text="課題プリント、中間テスト、証明写真など",
                max_length=63,
                verbose_name="タイトル名",
            ),
        ),
    ]
