# Generated by Django 5.1.3 on 2024-11-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0004_remove_category_channel_id_category_webhook_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="webhook_url",
            field=models.CharField(max_length=128, verbose_name="Webhook Url"),
        ),
    ]
