# Generated by Django 5.1.3 on 2024-11-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0005_alter_category_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="embed_color",
            field=models.CharField(
                default="green", max_length=16, verbose_name="embed_color"
            ),
        ),
    ]
