# Generated by Django 5.1.3 on 2024-11-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0006_alter_memo_detail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="title",
            new_name="name",
        ),
    ]
