# Generated by Django 5.1.3 on 2024-11-19 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0007_rename_title_category_name_rename_title_subject_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="作成日時"
            ),
        ),
        migrations.AddField(
            model_name="memo",
            name="created_by",
            field=models.CharField(
                default="unknown", max_length=63, verbose_name="作成者"
            ),
        ),
        migrations.AddField(
            model_name="memo",
            name="updated_by",
            field=models.CharField(
                default="unknown", max_length=63, verbose_name="編集者"
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="変更日時"
            ),
        ),
    ]
