# Generated by Django 5.1.3 on 2024-11-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0008_memo_created_at_memo_created_by_memo_updated_by_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Memo",
            new_name="Schedule",
        ),
    ]
