# Generated by Django 5.1.3 on 2024-11-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0009_rename_memo_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="bs_color",
            field=models.CharField(
                default=1, max_length=32, verbose_name="Boostrap Color"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="bs_icon",
            field=models.CharField(
                default=0, max_length=32, verbose_name="Bootstrap Icon"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="channel_id",
            field=models.SlugField(
                default=3, max_length=20, verbose_name="チャンネルID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="カテゴリー名"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="created_by",
            field=models.CharField(
                default="unknown", max_length=64, verbose_name="作成者"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="title",
            field=models.CharField(
                help_text="課題プリント、中間テスト、証明写真など",
                max_length=64,
                verbose_name="タイトル名",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="updated_by",
            field=models.CharField(
                default="unknown", max_length=64, verbose_name="編集者"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=64, unique=True, verbose_name="教科名"),
        ),
    ]
