# Generated by Django 5.1.3 on 2024-11-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0010_category_bs_color_category_bs_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="deadline",
            field=models.DateField(help_text="20XX-XX-XX", verbose_name="締め切り日"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="変更日時"),
        ),
    ]
