# Generated by Django 5.1.3 on 2024-11-15 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="お知らせのタイトル",
                        max_length=127,
                        verbose_name="Notice title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="お知らせの内容",
                        verbose_name="Notice content",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date created"
                    ),
                ),
            ],
        ),
    ]
