# Generated by Django 5.1.3 on 2024-11-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="description",
                    ),
                ),
            ],
        ),
    ]
