# Generated by Django 5.1.3 on 2024-11-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0002_discordbot"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DiscordBot",
            new_name="EmbedMessage",
        ),
    ]
