# Generated by Django 5.1.3 on 2024-11-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0003_rename_discordbot_embedmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedmessage",
            name="key",
            field=models.IntegerField(default=1, unique=True, verbose_name="key"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="embedmessage",
            name="title",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Title"
            ),
        ),
    ]
